import StoreProvider from "@/store/StoreProvider";
import "./globals.css";
import AppThemeProvider from "@/theme/theme-provider";
import DesktopHeader from "@/components/layout/DesktopHeader";
import MobileHeader from "@/components/layout/MobileHeader";
import Footer from "@/components/layout/Footer";
import { Box } from "@mui/material";
import MobileBottomNav from "@/components/layout/MobileBottomNav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <StoreProvider>
          <AppThemeProvider>
            <DesktopHeader />
            <MobileHeader />

            <Box component="main">{children}</Box>
            <Footer />
            <MobileBottomNav />
          </AppThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
